version: "3"
services:
 mysql:
   image: mysql:5.7
   volumes:
     - ./data:/var/lib/mysql
   restart: always
   ports:
    - 3309:3309
   environment:
     - MYSQL_ROOT_PASSWORD=root
 web:
   image: php:7.2-apache
   build:
    context: .
    dockerfile: Dockerfile-web
   depends_on:
     - mysql
   ports:
     - 50001:80
   links:
     - mysql:mysql
   volumes:
     - ./public:/var/www/html
 phpmyadmin:
   image: phpmyadmin/phpmyadmin
   ports:
     - 50002:80
   links:
     - mysql
   environment:
     - PMA_HOST=mysql
     - PMA_USER=root
     - PMA_PASSWORD=root